version: '3.8'

services:
  firebase-functions:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FIREBASE_CONFIG={"projectId":"glucosense-24-s2-07","storageBucket":"glucosense-24-s2-07.appspot.com","locationId":"us-central"}
      - GOOGLE_APPLICATION_CREDENTIALS="/app/serviceAccountKey.json"
    entrypoint: ["firebase", "emulators:start", "--only", "functions"]
