export const images = {
    welcome1: require('../assets/welcome-1.png'),
    welcome2: require('../assets/welcome-2.png'),
    welcome3: require('../assets/welcome-3.png'),
    logo: require('../assets/logo.png'),
    back: require('../assets/back(2).png'),
    headerQuestion1: require('../assets/headerQuestion1.png'),
    headerQuestion2: require('../assets/headerQuestion2.png'),
    headerQuestion3: require('../assets/headerQuestion3.png'),
    headerQuestion4: require('../assets/headerQuestion4.png'),
    headerQuestion5: require('../assets/headerQuestion5.png'),
    home: require('../assets/home.png'),
    insight: require('../assets/insight.png'),
    add: require('../assets/add.png'),
    food: require('../assets/food.png'),
    more: require('../assets/more.png'),
    reminder: require('../assets/reminder.png'),
  };